services:
#    esiea_blog.example:
#        class: Esiea\BlogBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    esiea_blog.antispam:
        class: Esiea\BlogBundle\Antispam\EsieaAntispam
        arguments: [50]
